stages:
  - test
  - build
  - test2
  - dev
  - stage
  - prod

install_env:
  stage: test
  script:
    - echo " test 1 -------------"

run_test:
  stage: test
  script:
    - echo " test 2 --------------"

linters:
  stage: test
  script:
    - echo " test linter -------------"

build:
  stage: build
  script:
    - cat init.txt
    - echo "running ./build.sh"

tests_after_build:
  stage: test2
  script: 
    - echo "test after build-----------"

deploy_dev:
  stage: dev
  script:
    - echo "Deploy dev+++++++"
  when: manual
deploy_stage:
  stege: stage
  script:
    - echo "Deploy stage++++++" 
  when: manual
  only:
    reft:
      - tags
      - master
      - /^release.*$/

deploy_prod:
  stade: prod
  scrip:
    - ./deploy.sh
  when: manual
  only:
    reft:
      - tags
      - master
      - /^release.*$/
